### ISSUE TITLE
Code example for Rule function seems to be incorrect

### ISSUE THREAD

**Issue by oredi** [freeformsystems/async-validate#20]
Hi,

May I checked if schema.error is correct? It appears to be undefined and when I checked lib/schema.js I see schema.ValidationError exposed but not schema.error

    var schema = require('async-validate');
    var ValidationError = schema.error;
    var descriptor = {
    .....

**Comment by freeformsystems** [comment]
My bad this changed in `0.2.x` I'll check the readme again, thanks.

**Comment by oredi** [comment]
I can do a PR for it if you want

**Comment by freeformsystems** [comment]
PR welcome, thanks.
