### ISSUE TITLE
npm run spec throws an error

### ISSUE THREAD

**Issue by oredi** [freeformsystems/async-validate#37]
npm run spec is throwing an error.
It appears that some requires for browserify no longer exists.
Are they no longer required?

```javascript
 require('./spec/transform');
-require('./spec/type');
 require('./spec/undef');
-require('./spec/validator');
```

**Comment by freeformsystems** [comment]
Good catch, thanks, fixed in d7711b3313d3f02377a0818fe5c257d74d458fdb.

Due to deleted test spec, updated for new test specs also.

**Comment by freeformsystems** [comment]
Furthermore, `require-dir` was not working with `browserify` so I shall write this file dynamically later, see #38.

**Comment by oredi** [comment]
actually I was looking to also update the developer section. Some npm modules like browserify and mdp needs to be install globally. That will be useful from newcomers to nodejs who might want to contribute

**Comment by freeformsystems** [comment]
Clarified requirements in 40e4f453aa7db4e789b4e201474c0bfa26d08e80, note that `browserify` is in devDependencies and the scripts should work fine after running `npm i`.

Thanks.
