### ISSUE TITLE
How can I pass diferent messages in min and max in the same validation? 

### ISSUE THREAD

**Issue by MarcosRava** [freeformsystems/async-validate#8]

**Comment by freeformsystems** [comment]
This is a little more convoluted then I would like as we don't actually know the *reason* for the failure when looking for the message in the rule, so I had to flag the error reason and then we can use an object as the rule message, ie:

```
{message: {min: '...', max: '...'}}
```

Implemented in `0.4.1`, see 806410eadcc567dfcc5c7b8555634ffc7ebfe197 and the test spec https://github.com/freeformsystems/async-validate/blob/master/test/spec/message-object.js.
